### PR TITLE
Fix rake tests on OS X

### LINKED ISSUE #8: bashcov tests fail on OS X
`bashcov`'s test suite fails on OS X.

It appears that the reason for this three fold:
1. File descriptors are not passed to scripts when they are executed directly (and the shebang is parsed and they are re-executed through bash).
2. `BASH_SOURCE` isn't always guaranteed to give an absolute path. It gives a relative path for our test cases on OS X.
3. `find -executable` is GNU specific

### PR DESCRIPTION
**Pull request by smspillaz**
There are some platform-related differences on OS X which cause bashcov not to work correctly, relating to differences between BASH_SOURCE, fd-passing and find.

Fixes #8

### CODE REVIEW

File: lib/bashcov/xtrace.rb [hunk 1]
```diff
@@ -13,7 +15,10 @@ class Xtrace
     # @see http://stackoverflow.com/questions/59895/can-a-bash-script-tell-what-directory-its-stored-in
     # @note We use a forward slash as delimiter since it's the only forbidden
     #   character in filenames on Unix and Windows.
-    PS4 = %Q{#{PREFIX}${BASH_SOURCE[0]}/${LINENO}: }
+    _READLINK = find_executable('readlink')
+    _GREADLINK = find_executable('greadlink')
+    READLINK = _GREADLINK.nil? ? _READLINK : _GREADLINK
+    PS4 = %Q{#{PREFIX}$(#{READLINK} -f ${BASH_SOURCE[0]})/${LINENO}: }
```
Comment (infertux) [inline lib/bashcov/xtrace.rb]: 1. I'm not a big fan of including `mkmf` here - it's supposed to be used in Makefile scripts and the like but not in "normal" Ruby code. If you look [here](https://github.com/ruby/ruby/blob/trunk/lib/mkmf.rb), you can see it defines a lot of top-level stuff and monkey-patches core types like `String`.


1. Why would you use `greadlink`? Isn't `readlink` available on OS X?


1. Doesn't bash find the path to `readlink` if you simply do `PS4 = %Q{#{PREFIX}$(readlink -f ${BASH_SOURCE[0]})/${LINENO}: }`?


1. If not, does it work using something like `READLINK = IO.popen("whereis -b readlink").read.match(/\Areadlink:\s([^\s]+)/).captures.first`? I know it's kinda ugly and I'm sure there is a better way to do that but you get the idea.

File: spec/bashcov/runner_spec.rb [hunk 2]
```diff
@@ -2,7 +2,8 @@
 require 'benchmark'
 
 describe Bashcov::Runner do
-  let(:runner) { Bashcov::Runner.new test_suite }
+  suite = test_suite
```
Comment (infertux) [inline spec/bashcov/runner_spec.rb]: Do you really need that? What about `let(:runner) { Bashcov::Runner.new "bash #{test_suite}" }`?

File: spec/test_app/test_suite.sh [hunk 3]
```diff
@@ -2,5 +2,4 @@
 
 cd $(dirname $0)
 
-find scripts -type f -executable -exec '{}' \;
-
+find scripts -type f -perm -111 -exec bash '{}' \;
```
Comment (infertux) [inline spec/test_app/test_suite.sh]: Here's an excerpt of the man of _GNU find_:

```
       -perm -mode
              All of the permission bits mode are set for the file.  Symbolic modes are accepted in this form, and this is usually the way in which would want to use them.  You must specify `u', `g' or `o'
              if you use a symbolic mode.   See the EXAMPLES section for some illustrative examples.

              
       -perm /mode
              Any of the permission bits mode are set for the file.  Symbolic modes are accepted in this form.  You must specify `u', `g' or `o' if you use a symbolic mode.  See the  EXAMPLES  section  for
              some illustrative examples.  If no permission bits in mode are set, this test matches any file (the idea here is to be consistent with the behaviour of -perm -000).


       -perm +mode
              This is no longer supported (and has been deprecated since 2005).  Use -perm /mode instead.
```

Note that the `-executable` flag in _GNU find_ tests that the file can be executed by the current user. Since we can't test this specifically with `-perm`, I think it'd be more bulletproof to use `-perm /111`. But I wonder if that is supported on OS X?

**Comment by infertux** [comment]
Just wanted to add that this is great work @smspillaz and I don't mean to scare you away with my comments :stuck_out_tongue_closed_eyes:. I'm just trying to do cross-compatibility properly...

**Comment by smspillaz** [comment]
No problem, I haven't really written any ruby code before in any serious
capacity - so all feedback is good feedback.

File: spec/test_app/test_suite.sh (hunk 3 above)
Comment (smspillaz) [inline spec/test_app/test_suite.sh]: BSD's `find` manpage:
 
     -perm [-|+]mode
             The mode may be either symbolic (see chmod(1)) or an octal number.  If the mode is symbolic, a
             starting value of zero is assumed and the mode sets or clears permissions without regard to the
             process' file mode creation mask.  If the mode is octal, only bits 07777 (S_ISUID | S_ISGID |
             S_ISTXT | S_IRWXU | S_IRWXG | S_IRWXO) of the file's mode bits participate in the comparison.
             If the mode is preceded by a dash (``-''), this primary evaluates to true if at least all of
             the bits in the mode are set in the file's mode bits.  If the mode is preceded by a plus
             (``+''), this primary evaluates to true if any of the bits in the mode are set in the file's
             mode bits.  Otherwise, this primary evaluates to true if the bits in the mode exactly match the
             file's mode bits.  Note, the first character of a symbolic mode may not be a dash (``-'').

It looks like `/mode` is not supported :/. There's `+mode`, which I'm sure does the same thing on GNU find, but that's deprecated on the latter.

I suppose `-mode` is not too bad in this case - we can control the permissions of the test files.

File: spec/bashcov/runner_spec.rb (hunk 2 above)
Comment (smspillaz) [inline spec/bashcov/runner_spec.rb]: Good idea - I didn't know you could do that with functions. Fixed.

File: lib/bashcov/xtrace.rb (hunk 1 above)
Comment (smspillaz) [inline lib/bashcov/xtrace.rb]: Yeah, the `readlink` compatibility fiasco is a little annoying :/. Basically, the version of readlink shipped on OS X is not useful at all - the GNU version always prints the absolute path to the file, the BSD version prints the absolute path to the file only if the file was a symlink. It also doesn't have an option to follow symlinks.

Its possible to install the GNU version of coreutils on OS X, which I understand that most developers do, because the BSD equivalents are very lacking. They're all prefixed with a "g". Hence the reason why we'd find `greadlink`first and then find `readlink`. 

That said, after having read about `mkmf` and friends, I've decided to remove the readlink solution and replaced it with something that's a little slower than `readlink` but should work in our case -` $(cd $(dirname ${BASH_SOURCE[0]}); pwd)/$(basename ${BASH_SOURCE[0]})`. It won't follow symlinks, but it does get you the absolute path.

**Comment by infertux** [comment]
Good stuff! :+1:
